import { collection, doc, getDoc, getDocs, setDoc, writeBatch } from 'firebase/firestore';
import { auth, db } from '../../lib/firebase';
import { sanitizeFirestoreData } from '../../lib/firestoreUtils';
import { AuditService } from '../../services/AuditService';
import type { MasterBackupRecord, MasterFinancialEntry, MasterGlobalSettings, MasterIntegrationStatus, MasterInvoiceRecord, MasterLead, MasterLeadStatus, MasterSupportTicket } from '../types/master';

const COLLECTIONS = { leads: 'master_leads', receivables: 'master_finance_receivables', payables: 'master_finance_payables', invoices: 'master_nfse', support: 'master_support_tickets', integrations: 'master_integrations', backups: 'master_backups', settings: 'master_settings' } as const;
const nowIso = () => new Date().toISOString();
const newId = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
async function listCollection<T>(name: string): Promise<T[]> { const snapshot = await getDocs(collection(db, name)); return snapshot.docs.map((item) => ({ id: item.id, ...item.data() } as T)); }
function audit(action: 'CREATE' | 'UPDATE' | 'DELETE', description: string, moduleName: string, targetEntity: string, companyId?: string) { return AuditService.log({ action, description, moduleName, targetEntity, companyId }); }

export class MasterOperationalService {
  static async loadOverview() { const [leads, receivables, payables, integrations, backups] = await Promise.all([this.listLeads(), this.listFinancialEntries('RECEBER'), this.listFinancialEntries('PAGAR'), this.listIntegrations(), this.listBackups()]); return { leads, receivables, payables, integrations, backups }; }
  static listLeads(): Promise<MasterLead[]> { return listCollection<MasterLead>(COLLECTIONS.leads); }
  static async saveLead(input: Partial<MasterLead>): Promise<MasterLead> {
    const id = input.id || newId('lead'); const current = input.id ? await getDoc(doc(db, COLLECTIONS.leads, id)) : null; const uid = auth.currentUser?.uid || 'system';
    const lead: MasterLead = { id, name: String(input.name || '').trim(), companyName: String(input.companyName || '').trim(), cnpj: String(input.cnpj || '').trim(), phone: String(input.phone || '').trim(), email: String(input.email || '').trim().toLowerCase(), source: input.source || 'MANUAL', interest: String(input.interest || '').trim(), ownerId: input.ownerId || uid, ownerName: input.ownerName || auth.currentUser?.displayName || auth.currentUser?.email || '', notes: String(input.notes || '').trim(), status: input.status || 'NOVO', companyId: input.companyId || '', history: Array.isArray(input.history) ? input.history : [], createdAt: current?.exists() ? String(current.data().createdAt || nowIso()) : nowIso(), updatedAt: nowIso(), createdBy: input.createdBy || uid, updatedBy: uid };
    if (!lead.name || !lead.email) throw new Error('Nome e e-mail são obrigatórios para o lead.'); await setDoc(doc(db, COLLECTIONS.leads, id), sanitizeFirestoreData(lead), { merge: true }); await audit(current?.exists() ? 'UPDATE' : 'CREATE', `Lead ${lead.name} salvo com status ${lead.status}`, 'Leads', 'Lead', lead.companyId); return lead;
  }
  static updateLeadStatus(lead: MasterLead, status: MasterLeadStatus, companyId?: string) { const uid = auth.currentUser?.uid || 'system'; return this.saveLead({ ...lead, status, companyId: companyId || lead.companyId, history: [...(lead.history || []), { at: nowIso(), action: `STATUS_${status}`, userId: uid }] }); }
  static listFinancialEntries(type: 'RECEBER' | 'PAGAR'): Promise<MasterFinancialEntry[]> { return listCollection<MasterFinancialEntry>(type === 'RECEBER' ? COLLECTIONS.receivables : COLLECTIONS.payables); }
  static async saveFinancialEntry(input: Partial<MasterFinancialEntry> & { type: 'RECEBER' | 'PAGAR' }): Promise<MasterFinancialEntry> {
    const id = input.id || newId(input.type === 'RECEBER' ? 'receber' : 'pagar'); const collectionName = input.type === 'RECEBER' ? COLLECTIONS.receivables : COLLECTIONS.payables; const existing = input.id ? await getDoc(doc(db, collectionName, id)) : null; const uid = auth.currentUser?.uid || 'system';
    const entry: MasterFinancialEntry = { id, type: input.type, description: String(input.description || '').trim(), category: String(input.category || '').trim(), companyId: String(input.companyId || '').trim(), companyName: String(input.companyName || '').trim(), supplier: String(input.supplier || '').trim(), amount: Number(input.amount || 0), dueDate: String(input.dueDate || ''), paidAt: input.paidAt || '', paymentMethod: input.paymentMethod || '', status: input.status || 'PENDENTE', externalId: input.externalId || '', idempotencyKey: input.idempotencyKey || `manual:${input.type}:${id}`, notes: input.notes || '', createdAt: existing?.exists() ? String(existing.data().createdAt || nowIso()) : nowIso(), updatedAt: nowIso(), createdBy: input.createdBy || uid, updatedBy: uid };
    if (!entry.description || !entry.dueDate || entry.amount <= 0) throw new Error('Descrição, valor maior que zero e vencimento são obrigatórios.'); await setDoc(doc(db, collectionName, id), sanitizeFirestoreData(entry), { merge: true }); await audit(existing?.exists() ? 'UPDATE' : 'CREATE', `${entry.type === 'RECEBER' ? 'Receita' : 'Despesa'} ${entry.description} salva`, 'Financeiro Master', entry.type, entry.companyId); return entry;
  }
  static listInvoices(): Promise<MasterInvoiceRecord[]> { return listCollection<MasterInvoiceRecord>(COLLECTIONS.invoices); }
  static listSupportTickets(): Promise<MasterSupportTicket[]> { return listCollection<MasterSupportTicket>(COLLECTIONS.support); }
  static async saveSupportTicket(input: Partial<MasterSupportTicket>): Promise<MasterSupportTicket> {
    const id = input.id || newId('support'); const existing = input.id ? await getDoc(doc(db, COLLECTIONS.support, id)) : null; const uid = auth.currentUser?.uid || 'system';
    const ticket: MasterSupportTicket = { id, companyId: String(input.companyId || '').trim(), companyName: String(input.companyName || '').trim(), subject: String(input.subject || '').trim(), description: String(input.description || '').trim(), status: input.status || 'ABERTO', priority: input.priority || 'NORMAL', responsibleId: input.responsibleId || uid, responsibleName: input.responsibleName || auth.currentUser?.displayName || auth.currentUser?.email || '', guidance: input.guidance || '', createdAt: existing?.exists() ? String(existing.data().createdAt || nowIso()) : nowIso(), updatedAt: nowIso(), createdBy: input.createdBy || uid, updatedBy: uid };
    if (!ticket.companyId || !ticket.subject || !ticket.description) throw new Error('Empresa, assunto e descrição são obrigatórios.'); await setDoc(doc(db, COLLECTIONS.support, id), sanitizeFirestoreData(ticket), { merge: true }); await audit(existing?.exists() ? 'UPDATE' : 'CREATE', `Atendimento ${ticket.subject} salvo`, 'Suporte Técnico', 'Atendimento', ticket.companyId); return ticket;
  }
  static async listIntegrations(): Promise<MasterIntegrationStatus[]> {
    const records = await listCollection<MasterIntegrationStatus>(COLLECTIONS.integrations);
    // OpenAI é registro legado e não pode declarar o Gemini como conectado.
    // Somente um registro real Gemini é reaproveitado pelo card legado da view durante a migração visual.
    return records.filter((item) => item.name.trim().toLowerCase() !== 'openai / ia').map((item) => /gemini/i.test(item.name) ? { ...item, name: 'OpenAI / IA' } : item);
  }
  static listBackups(): Promise<MasterBackupRecord[]> { return listCollection<MasterBackupRecord>(COLLECTIONS.backups); }
  static async getSettings(): Promise<MasterGlobalSettings> { const snapshot = await getDoc(doc(db, COLLECTIONS.settings, 'global')); if (!snapshot.exists()) return { id: 'global', platformName: 'RL Connect', billingPeriodDays: 30, gracePeriodDays: 10 }; const data = snapshot.data() as Partial<MasterGlobalSettings>; return { id: 'global', platformName: String(data.platformName || 'RL Connect'), billingPeriodDays: Number(data.billingPeriodDays || 30), gracePeriodDays: Number(data.gracePeriodDays || 10), supportEmail: String(data.supportEmail || ''), privacyPolicyUrl: String(data.privacyPolicyUrl || ''), termsUrl: String(data.termsUrl || ''), updatedAt: data.updatedAt, updatedBy: data.updatedBy }; }
  static async saveSettings(input: MasterGlobalSettings): Promise<MasterGlobalSettings> { const settings = { ...input, id: 'global' as const, billingPeriodDays: 30, gracePeriodDays: 10, updatedAt: nowIso(), updatedBy: auth.currentUser?.uid || 'system' }; await setDoc(doc(db, COLLECTIONS.settings, 'global'), sanitizeFirestoreData(settings), { merge: true }); await audit('UPDATE', 'Configurações globais atualizadas', 'Configurações', 'Configuração Global'); return settings; }
  static async registerPaymentOnce(input: { entry: MasterFinancialEntry; paymentId: string; paidAt?: string }): Promise<boolean> {
    const key = input.paymentId.trim(); if (!key) throw new Error('Identificador do pagamento é obrigatório.'); const idempotencyRef = doc(db, 'master_idempotency', `payment_${key}`); const existing = await getDoc(idempotencyRef); if (existing.exists()) return false;
    const entryRef = doc(db, COLLECTIONS.receivables, input.entry.id); const batch = writeBatch(db); batch.set(idempotencyRef, { type: 'PAYMENT', paymentId: key, createdAt: nowIso() }); batch.set(entryRef, { status: 'PAGO', paidAt: input.paidAt || nowIso(), externalId: key, updatedAt: nowIso() }, { merge: true }); batch.set(doc(db, 'auditLogs', newId('log')), { actionType: 'UPDATE', description: `Pagamento ${key} confirmado sem duplicidade`, moduleName: 'Financeiro Master', targetEntity: input.entry.id, companyId: input.entry.companyId || '', createdAt: nowIso(), updatedAt: nowIso(), createdBy: auth.currentUser?.uid || 'system', status: 'ativo' }); await batch.commit(); return true;
  }
}
