import React, { useState } from 'react';
import { Save, X } from 'lucide-react';
import type { SaaSPlan } from '../types/master';

export function MasterEditPlanModal({ plan, onClose, onSave }: { plan: SaaSPlan; onClose: () => void; onSave: (plan: SaaSPlan) => Promise<void> | void }) {
  const [form, setForm] = useState<SaaSPlan>({ ...plan, includedModules: [...plan.includedModules] });
  const [saving, setSaving] = useState(false);
  const input = 'w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white';
  return <div className="fixed inset-0 z-[85] flex items-center justify-center bg-black/70 p-4"><form onSubmit={async (e) => { e.preventDefault(); setSaving(true); try { await onSave(form); } finally { setSaving(false); } }} className="w-full max-w-xl rounded-2xl border border-slate-700 bg-slate-900 p-5 text-white"><div className="flex items-center justify-between"><h2 className="font-black">Editar plano</h2><button type="button" onClick={onClose}><X className="h-5 w-5" /></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-slate-400">Nome<input className={`${input} mt-1`} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value as SaaSPlan['name'] })} /></label><label className="text-xs font-bold text-slate-400">Preço mensal<input type="number" step="0.01" min="0" className={`${input} mt-1`} value={form.monthlyPrice} onChange={(e) => setForm({ ...form, monthlyPrice: Number(e.target.value) })} /></label><label className="text-xs font-bold text-slate-400">Máx. usuários<input type="number" min="0" className={`${input} mt-1`} value={form.maxUsers} onChange={(e) => setForm({ ...form, maxUsers: Number(e.target.value) })} /></label><label className="text-xs font-bold text-slate-400">Máx. vagas<input type="number" min="0" className={`${input} mt-1`} value={form.maxActiveJobs} onChange={(e) => setForm({ ...form, maxActiveJobs: Number(e.target.value) })} /></label><label className="text-xs font-bold text-slate-400">Máx. colaboradores<input type="number" min="0" className={`${input} mt-1`} value={form.maxEmployees} onChange={(e) => setForm({ ...form, maxEmployees: Number(e.target.value) })} /></label><label className="text-xs font-bold text-slate-400">Status<select className={`${input} mt-1`} value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as SaaSPlan['status'] })}><option>Ativo</option><option>Rascunho</option><option>Arquivado</option></select></label><label className="sm:col-span-2 text-xs font-bold text-slate-400">Descrição<textarea className={`${input} mt-1`} rows={3} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-xl border border-slate-700 px-4 py-2 text-sm font-bold">Cancelar</button><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-amber-500 px-4 py-2 text-sm font-black text-slate-950"><Save className="h-4 w-4" />Salvar</button></div></form></div>;
}
