import React, { useEffect, useState } from 'react';
import { Save, X } from 'lucide-react';
import type { PlatformModule } from '../types/master';

const blankModule = (): PlatformModule => ({ id: '', key: '', name: '', category: 'Ferramentas', description: '', status: 'Ativo', isCore: false, activeTenantsCount: 0, iconName: 'Layers', route: '', displayOrder: 99 });

export function MasterCreateModuleModal({ isOpen, onClose, initialModule, onSave }: { isOpen: boolean; onClose: () => void; initialModule?: PlatformModule; onSave: (module: PlatformModule) => Promise<void> | void }) {
  const [form, setForm] = useState<PlatformModule>(() => initialModule ? { ...initialModule } : blankModule());
  const [saving, setSaving] = useState(false);
  useEffect(() => setForm(initialModule ? { ...initialModule } : blankModule()), [initialModule]);
  if (!isOpen) return null;
  const input = 'w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white';
  return <div className="fixed inset-0 z-[85] flex items-center justify-center bg-black/70 p-4"><form onSubmit={async (e) => { e.preventDefault(); if (!form.key.trim() || !form.name.trim()) return; setSaving(true); try { await onSave({ ...form, id: form.id || form.key.trim() }); } finally { setSaving(false); } }} className="w-full max-w-xl rounded-2xl border border-slate-700 bg-slate-900 p-5 text-white"><div className="flex items-center justify-between"><h2 className="font-black">{initialModule ? 'Editar módulo' : 'Novo módulo'}</h2><button type="button" onClick={onClose}><X className="h-5 w-5" /></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-slate-400">Nome<input required className={`${input} mt-1`} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label className="text-xs font-bold text-slate-400">Chave<input required className={`${input} mt-1`} value={form.key} onChange={(e) => setForm({ ...form, key: e.target.value })} disabled={Boolean(initialModule?.id)} /></label><label className="text-xs font-bold text-slate-400">Categoria<input className={`${input} mt-1`} value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value as PlatformModule['category'] })} /></label><label className="text-xs font-bold text-slate-400">Status<select className={`${input} mt-1`} value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as PlatformModule['status'] })}><option>Ativo</option><option>Beta</option><option>Em Desenvolvimento</option><option>Desativado</option><option>Inativo</option></select></label><label className="text-xs font-bold text-slate-400">Rota<input className={`${input} mt-1`} value={form.route || ''} onChange={(e) => setForm({ ...form, route: e.target.value })} /></label><label className="text-xs font-bold text-slate-400">Ordem<input type="number" className={`${input} mt-1`} value={form.displayOrder || 99} onChange={(e) => setForm({ ...form, displayOrder: Number(e.target.value) })} /></label><label className="sm:col-span-2 text-xs font-bold text-slate-400">Descrição<textarea rows={3} className={`${input} mt-1`} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-xl border border-slate-700 px-4 py-2 text-sm font-bold">Cancelar</button><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-amber-500 px-4 py-2 text-sm font-black text-slate-950"><Save className="h-4 w-4" />Salvar</button></div></form></div>;
}
