from pathlib import Path


def replace_once(path: str, old: str, new: str):
    p = Path(path)
    text = p.read_text(encoding='utf-8')
    if old not in text:
        raise SystemExit(f'Pattern not found in {path}: {old[:160]!r}')
    p.write_text(text.replace(old, new, 1), encoding='utf-8')

# DP: validate CPF/salary before trying to persist admission.
path = 'src/components/views/DepartamentoPessoalView.tsx'
replace_once(path, "import { dataService } from '../../services/dataService';\n", "import { dataService } from '../../services/dataService';\nimport { isValidCpfForAdmission } from '../../services/businessRules';\n")
replace_once(path, "  const [salarioFunc, setSalarioFunc] = useState(9500);\n", "  const [salarioFunc, setSalarioFunc] = useState(9500);\n  const [formError, setFormError] = useState('');\n")
replace_once(path, "  const handleCreateFuncionario = (e: React.FormEvent) => {\n    e.preventDefault();\n    if (!nomeFunc || !cpfFunc) return;\n\n    dataService.createFuncionario({", "  const handleCreateFuncionario = (e: React.FormEvent) => {\n    e.preventDefault();\n    setFormError('');\n    if (!nomeFunc.trim()) { setFormError('Informe o nome completo do colaborador.'); return; }\n    if (!isValidCpfForAdmission(cpfFunc)) { setFormError('Informe um CPF no formato 000.000.000-00 ou apenas 11 dígitos.'); return; }\n    if (!Number.isFinite(salarioFunc) || salarioFunc <= 0) { setFormError('Informe um salário maior que zero para concluir a admissão.'); return; }\n\n    dataService.createFuncionario({")
replace_once(path, "    setCargoFunc('');\n    refreshData();", "    setCargoFunc('');\n    setFormError('');\n    refreshData();")
replace_once(path, "                  const cpf = window.prompt('Informe o CPF do colaborador para concluir a admissão:') || '';\n                  if (!cpf.trim()) return;\n                  const salarioStr = window.prompt('Informe o salário de admissão:', String(adm.salario_sugerido || 0)) || '';\n                  const salario = Number(salarioStr.replace(',', '.'));\n                  const result = dataService.concluirAdmissao(adm.id, cpf, salario);\n                  if (!result) window.alert('Não foi possível concluir a admissão. Confira CPF e salário.');", "                  const cpf = window.prompt('Informe o CPF do colaborador para concluir a admissão:') || '';\n                  if (!cpf.trim()) return;\n                  if (!isValidCpfForAdmission(cpf)) { window.alert('CPF inválido. Use 000.000.000-00 ou apenas 11 dígitos.'); return; }\n                  const salarioStr = window.prompt('Informe o salário de admissão:', String(adm.salario_sugerido || 0)) || '';\n                  const salario = Number(salarioStr.replace(/\\./g, '').replace(',', '.'));\n                  if (!Number.isFinite(salario) || salario <= 0) { window.alert('Salário inválido. Informe um valor maior que zero.'); return; }\n                  const result = dataService.concluirAdmissao(adm.id, cpf, salario);\n                  if (!result) window.alert('Não foi possível concluir a admissão. Os dados continuam pendentes para correção; nada foi perdido.');")
replace_once(path, "              <div className=\"mt-6 flex justify-end", "              {formError && <div className=\"rounded-xl border border-rose-200 bg-rose-50 p-3 font-semibold text-rose-700\">{formError}</div>}\n\n              <div className=\"mt-6 flex justify-end")

# Headhunter: expose and validate fee before client/commercial data is accepted.
path = 'src/components/views/HeadhunterView.tsx'
replace_once(path, "import { dataService } from '../../services/dataService';\n", "import { dataService } from '../../services/dataService';\nimport { parseFeeRule } from '../../services/businessRules';\n")
replace_once(path, "  const [taxaCliente, setTaxaCliente] = useState('20% do análogo salarial');\n", "  const [taxaCliente, setTaxaCliente] = useState('20% do salário');\n  const [clienteError, setClienteError] = useState('');\n")
replace_once(path, "  const handleCreateCliente = (e: React.FormEvent) => {\n    e.preventDefault();\n    if (!nomeCliente || !cnpjCliente) return;\n\n    dataService.createCliente({", "  const handleCreateCliente = (e: React.FormEvent) => {\n    e.preventDefault();\n    setClienteError('');\n    if (!nomeCliente.trim()) { setClienteError('Informe o nome da empresa cliente.'); return; }\n    const documento = cnpjCliente.replace(/\\D/g, '');\n    if (documento.length !== 14) { setClienteError('Informe um CNPJ com 14 dígitos.'); return; }\n    if (!parseFeeRule(taxaCliente)) { setClienteError('Configure um fee válido e maior que zero. Exemplos: 35%, R$ 1.750 fixo ou 1,5x salário.'); return; }\n\n    dataService.createCliente({")
replace_once(path, "    setResponsavelCliente('');\n    refreshData();", "    setResponsavelCliente('');\n    setTaxaCliente('20% do salário');\n    setClienteError('');\n    refreshData();")
replace_once(path, "              <div className=\"mt-6 flex justify-end gap-3", "              <div>\n                <label className=\"font-bold text-slate-700\">Fee / Honorário *</label>\n                <input\n                  type=\"text\"\n                  required\n                  value={taxaCliente}\n                  onChange={(e) => setTaxaCliente(e.target.value)}\n                  placeholder=\"Ex: 35%, R$ 1.750 fixo ou 1,5x salário\"\n                  className=\"mt-1 w-full rounded-xl border border-slate-200 p-2.5 text-xs focus:border-indigo-500 focus:outline-none\"\n                />\n                <p className=\"mt-1 text-[10px] text-slate-500\">O financeiro só libera AGUARDANDO_COBRANCA quando o fee resultar em valor maior que zero.</p>\n              </div>\n\n              {clienteError && <div className=\"rounded-xl border border-rose-200 bg-rose-50 p-3 font-semibold text-rose-700\">{clienteError}</div>}\n\n              <div className=\"mt-6 flex justify-end gap-3")
replace_once(path, "                  <p className=\"mt-2 text-base font-black text-emerald-700\">{c.valor ? `R$ ${Number(c.valor).toLocaleString('pt-BR', { minimumFractionDigits: 2 })}` : 'Fee não configurado'}</p>", "                  <p className=\"mt-2 text-base font-black text-emerald-700\">{c.valor ? `R$ ${Number(c.valor).toLocaleString('pt-BR', { minimumFractionDigits: 2 })}` : 'Aguardando dados comerciais'}</p>\n                  {!c.valor && <p className=\"mt-1 text-amber-700\">Revise salário e fee da vaga. A contratação permanece salva e não gera cobrança incorreta.</p>}")

print('Friendly validation patch applied.')
