import React,{useEffect,useState} from 'react';
import {Header} from './components/Header';import {Sidebar,ViewTab} from './components/Sidebar';import {FirebaseLoginView} from './components/FirebaseLoginView';import {dataService} from './services/dataService';
import {DashboardView} from './components/views/DashboardView';import {MasterAdminView} from './components/views/MasterAdminView';import {RecruitmentView} from './components/views/RecruitmentView';import {HeadhunterView} from './components/views/HeadhunterView';import {PublicPortalView} from './components/views/PublicPortalView';import {PublicCompanyPortal} from './components/views/PublicCompanyPortal';import {AiScreeningView} from './components/views/AiScreeningView';import {AgendaView} from './components/views/AgendaView';import {DepartamentoPessoalView} from './components/views/DepartamentoPessoalView';import {AuditLogsView} from './components/views/AuditLogsView';import {CompanySettingsView} from './components/views/CompanySettingsView';import {MasterBuilderView} from './components/views/MasterBuilderView';
function publicCompanyFromUrl(){const p=location.pathname.match(/\/vagas\/([^/?#]+)/);const h=location.hash.match(/#\/vagas\/([^/?#]+)/);return decodeURIComponent(p?.[1]||h?.[1]||'')||null}
export function App(){const[currentTab,setCurrentTab]=useState<ViewTab>('dashboard');const[status,setStatus]=useState(dataService.getFirebaseStatus());const[publicEmpresaId,setPublicEmpresaId]=useState<string|null>(publicCompanyFromUrl);const[publicReady,setPublicReady]=useState(false);
 useEffect(()=>dataService.subscribe(()=>setStatus(dataService.getFirebaseStatus())),[]);useEffect(()=>{const h=()=>setPublicEmpresaId(publicCompanyFromUrl());addEventListener('popstate',h);addEventListener('hashchange',h);return()=>{removeEventListener('popstate',h);removeEventListener('hashchange',h)}},[]);useEffect(()=>{if(!publicEmpresaId){setPublicReady(false);return}let live=true;setPublicReady(false);dataService.loadPublicPortalFirebase(publicEmpresaId).finally(()=>live&&setPublicReady(true));return()=>{live=false}},[publicEmpresaId]);
 if(publicEmpresaId){if(!publicReady)return <div className="min-h-screen grid place-items-center bg-slate-50">Carregando vagas no Firebase...</div>;return <PublicCompanyPortal empresaId={publicEmpresaId} onBackToApp={()=>{history.pushState({},'','/');setPublicEmpresaId(null);setCurrentTab('dashboard')}}/>}if(!status.ready)return <div className="min-h-screen grid place-items-center bg-slate-50">Validando sessão Firebase...</div>;if(!status.authenticated)return <FirebaseLoginView error={status.error}/>;
 return <div className="flex min-h-screen bg-slate-50 font-sans text-slate-900 antialiased"><Sidebar currentTab={currentTab} onSelectTab={setCurrentTab}/><div className="flex flex-1 flex-col overflow-x-hidden"><Header onNavigateTab={setCurrentTab} currentTab={currentTab}/><main className="flex-1 w-full mx-auto p-4 sm:p-6 lg:p-8 max-w-7xl">{currentTab==='dashboard'&&<DashboardView onNavigateTab={setCurrentTab}/>} {currentTab==='master_admin'&&<MasterAdminView/>}{currentTab==='construtor_ia'&&<MasterBuilderView/>}{currentTab==='recrutamento'&&<RecruitmentView/>}{currentTab==='headhunter'&&<HeadhunterView/>}{currentTab==='portal_vagas'&&<PublicPortalView/>}{currentTab==='ia_screening'&&<AiScreeningView/>}{currentTab==='agenda'&&<AgendaView/>}{currentTab==='departamento_pessoal'&&<DepartamentoPessoalView/>}{currentTab==='audit_logs'&&<AuditLogsView/>}{currentTab==='settings'&&<CompanySettingsView/>}</main></div></div>}
export default App;
